server:
  port: 9191

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/v1/students/**
        - id: school-service
          uri: lb://school-service
          predicates:
            - Path=/api/v1/schools/**

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0